<a href="https://colab.research.google.com/github/FatimaaShahid/Machine-Learning-Labs-CS-324-/blob/main/Lab1%5CML_LAB_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
#one way
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
print(arr1)

#another way
ar1 = np.array( [6,7.5,8,0,1])
ar1


[6.  7.5 8.  0.  1. ]


array([6. , 7.5, 8. , 0. , 1. ])

In [ ]:
arr1.shape

(5,)

In [ ]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
arr2.shape


(2, 4)

In [ ]:
z1 = np.zeros(4) #1d
print(z1)
print()
z2 = np.zeros((3,6)) #2d
print(z2)
print()
z3 = np.zeros((2,3,2)) #(blocks,rows,column) for 3d
print(z3)
#np.empty → fills with whatever is already in memory (garbage values), syntax same

[0. 0. 0. 0.]

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [ ]:
#.astype cast every element to the desired cast, without modifying the actual list
float_arr = arr2.astype(np.float64)
print(arr2.dtype)
print(float_arr.dtype)



int64
float64


In [ ]:
#float to int; decimal point values will be truncated
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr)
new = arr.astype(np.int32)
new


[ 3.7 -1.2 -2.6  0.5 12.9 10.1]


array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [ ]:
#we can match the data type as per another array as well
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50],
dtype=np.float64)
match = int_array.astype(calibers.dtype)
print(int_array.dtype)
print(calibers.dtype)
match.dtype

int64
float64


dtype('float64')

In [ ]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr*0.5

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [ ]:
arr = np.arange(10)
print(arr)
print(arr[5:8])
arr[5:8] = 12
print(arr)
arr_slice = arr[5:8]
print(arr_slice)
arr_slice[1] = 12345
print(arr_slice)
print(arr)

#data is not copied, and any modifications to the view will be reflected in the
#source array:

#in order to not modify the actual use .copy() and save to another variable

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]
[12 12 12]
[   12 12345    12]
[    0     1     2     3     4    12 12345    12     8     9]


In [ ]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
arr2d[:2, 1:] #rows, col


array([[2, 3],
       [5, 6]])

### Q2

In [3]:
Data1 = np.array([1,3,9,12,18])
Data2 = np.array([[1,5,2,0],
                  [3,6,4,7]])
Data3 = np.array([['7','6'],
                 ['5','4'],
                  ['3','2']])
Data4 = np.array([[11,52,20,50],
                  [34,61,43,17]])
print(Data1)
print(Data2)
print(Data3)
print(Data4)


[ 1  3  9 12 18]
[[1 5 2 0]
 [3 6 4 7]]
[['7' '6']
 ['5' '4']
 ['3' '2']]
[[11 52 20 50]
 [34 61 43 17]]


###Q3

In [4]:
print(Data1+Data1)
print(Data1*10)
print(Data1.astype(int))
print(Data2.astype(int))
print(Data3.astype(int))
print(Data4.astype(int))

[ 2  6 18 24 36]
[ 10  30  90 120 180]
[ 1  3  9 12 18]
[[1 5 2 0]
 [3 6 4 7]]
[[7 6]
 [5 4]
 [3 2]]
[[11 52 20 50]
 [34 61 43 17]]
